apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hivebox.fullname" . }}
  labels:
    app: HiveBox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: HiveBox
  template:
    metadata:
      labels:
        app: HiveBox
    spec:
      containers:
        - name: hivebox-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: BASE_URL
              value: {{ .Values.env.baseUrl | quote }}
            - name: BOX_ID
              value: {{ .Values.env.boxId | quote }}
            - name: VALKEY_HOST
              value: {{ .Values.env.valkeyHost | quote }}
            - name: VALKEY_PORT
              value: {{ .Values.env.valkeyPort | quote }}
            - name: VALKEY_TTL
              value: {{ .Values.env.valkeyTtl | quote }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.env.minioEndpoint | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.env.minioAccessKey | quote }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.env.minioSecretKey | quote }}
            - name: MINIO_BUCKET
              value: {{ .Values.env.minioBucket | quote }}
          resources:
            limits:
              memory: "512M"
              cpu: "500m"
            requests:
              memory: "256M"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /version
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
