replicaCount: 1

image:
  repository: hivebox
  tag: local
  pullPolicy: Never


env:
  baseUrl: "https://api.opensensemap.org"
  boxId: "5eba5fbad46fb8001b799786,5c21ff8f919bf8001adf2488,5ade1acf223bd80019a1011c"
  valkeyHost: "valkey-infra.valkey.svc.cluster.local"
  minioEndpoint: "minio-infra.minio.svc.cluster.local:9000"


ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: hivebox.local
      paths:
        - path: /
          pathType: ImplementationSpecific