apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox-deployment
  labels:
    app: HiveBox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HiveBox
  template:
    metadata:
      labels:
        app: HiveBox
    spec:
      containers:
        - name: hivebox-container
          image: ghcr.io/yannislrg/hivebox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: BASE_URL
              value: "https://api.opensensemap.org"
            - name: BOX_ID
              value: "5c21ff8f919bf8001adf2488,5ade1acf223bd80019a1011c"
            - name: MINIO_ENDPOINT
              value: "http://minio-infra.minio.svc.cluster.local:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: MINIO_BUCKET
              value: "hivebox-data"
            - name: VALKEY_HOST
              value: "valkey-infra-master.valkey.svc.cluster.local"
            - name: VALKEY_PORT
              value: "6379"
            - name: VALKEY_TTL
              value: "300"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /version
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10