apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox-deployment

spec:
  template:
    spec:
      containers:
        - name: hivebox-container
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000