apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-minio.yaml
  - namespace-valkey.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - apps/minio
  - apps/valkey
