apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: charts/redis-18.2.0

helmCharts:
  - name: redis
    releaseName: valkey-infra
    namespace: valkey
    version: 18.2.0
    valuesInline:
      auth:
        enabled: false
      architecture: standalone
      master:
        persistence:
          enabled: false
