apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-boxID.yml
    target:
      kind: Deployment
      name: hivebox-deployment
  - path: patch-ressources.yml
    target:
      kind: Deployment
      name: hivebox-deployment
