apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox-deployment

spec:
  template:
    spec:
      containers:
        - name: hivebox-container
          resources:
            limits:
              memory: "1024M"
              cpu: "1000m"
